export async function seed(knex) {
  //delete existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: "27da2058-dbc7-432f-b66a-f97e67f080e4",
      user_name: "Diya",
      pet_name: "Shadow",
      type: "Dog",
      breed: "mutt",
      avatar: "./dog_1.jpg",
      temperament: "social",
      status: "Vaccinated, Spayed",
      bio: "A sweet, tiny girl. She was rescued and is loved by the whole neighbourhood. She loves most dogs but can sometimes get a bit territorial",
      contact_phone: "+1 (123) 456-7890",
      contact_email: "diya@gmail.com",
      password: "$10$gqHshoxnqw4WXWWvlHu.SeC2QRWG64kYuHMGdiRPXEFoZ1CKRvf5e",
      location: "Burnaby, BC",
    },
    {
      id: "2c4bebd3-a8d1-449b-b648-fdd2a3851fd6",
      user_name: "Natasha",
      pet_name: "Lucy",
      type: "Dog",
      breed: "Labradoodle",
      avatar: "images/dog_2",
      temperament: "social",
      status: "Vaccinated",
      bio: "The sweetest rescue puppy ever, she loves her family and our dogs, but is a bit territorial with her favourite humans. She needs a bit more socialisation",
      contact_phone: "+1 (123) 456-7890",
      contact_email: "natasha@gmail.com",
      password: "$10$HIM7jJVWD4DjUA8URREW4elXB2ymRAwhw/zze1.oqGY3knQEIXTwC",
      location: "Richmond, BC",
    },
    {
      id: "8343f2fc-b5c0-4305-ac08-f8f339aa0610",
      user_name: "Anoshka",
      pet_name: "Bruno",
      type: "Dog",
      breed: "Cocker Spaniel",
      avatar: "images/dog_2",
      temperament: "shy",
      status: "Vaccinated",
      bio: "He's an old baby/. He loves his humans, and is supoer active. He's an all barks no bite dog. He takes a bit to befriend other dogs, and is looking for buddies who are calm, and not reactive, and are social",
      contact_phone: "+1 (123) 456-7890",
      contact_email: "anoshka@gmail.com",
      password: "$10$AVVKhS17OHcKNiHnnINUrOMW7AAEkpn7jvKU2/6pnekNqagj4wNZW",
      location: "Surrey, BC",
    },
    {
      id: "335c8874-a66a-474b-9121-269b76a0b841",
      user_name: "Melissa",
      pet_name: "Bella",
      type: "Dog",
      breed: "Golden Retriever",
      avatar: "images/dog_2",
      temperament: "friendly",
      status: "Vaccinated, Spayed",
      bio: "She loves everyone indiscriminately. She's a gentle soul and is patient with her little brothers and sisters. All she needs is food and love!",
      contact_phone: "+1 (123) 456-7890",
      contact_email: "melissa@gmail.com",
      password: "$10$AVVKhS17OHcKNiHnnINUrOMW7AAEkpn7jvKU2/6pnekNqagj4wNZW",
      location: "North Vancouver, BC",
    },
    {
      id: "1981842d-b01c-4452-a6da-0e032eead823",
      user_name: "Lane",
      pet_name: "Joe Shmidt",
      type: "Dog",
      breed: "Pitbull",
      avatar: "images/dog_2",
      temperament: "shy",
      status: "Vaccinated, Neutered",
      bio: "He's a sweet and quiet rescue puppy. He doesn't like loud noises and big crowds, but is comfortable witha  few friendly dogs.",
      contact_phone: "+1 (123) 456-7890",
      contact_email: "lane@gmail.com",
      password: "$10$AVVKhS17OHcKNiHnnINUrOMW7AAEkpn7jvKU2/6pnekNqagj4wNZW",
      location: "Mount Pleasant, BC",
    },
  ]);
}
